### ISSUE TITLE
How to exclude Foundation.kit classes and SPM classes?

### ISSUE THREAD

**Issue by hsleedevelop** [MarcoEidinger/SwiftPlantUML#34]
Hello~
Thank you for awesome tools and saving a ton of times.

How to exclude Foundation.kit classes and SPM classes?
I can't find the option.

**Comment by MarcoEidinger** [comment]
> Thank you for awesome tools and saving a ton of times.

Glad you like SwiftPlantUML :)

> How to exclude Foundation.kit classes and SPM classes?

I am not sure I understand. What do you mean by SPM classes? Also how do Foundation related classes appear? Do you mean by inheritance / type conformance? 

You can exclude inheritance relationships based on parent (wildcards supported), e.g. do not show inheritance to `Codable`. Also, you can include/exclude files (wildcards supported) of your own project and hide any extensions.

Example `.swiftplantuml.yml`

```yml
files:
    exclude:
    - "Tests/**/*.swift" # paths to ignore for diagram. Takes precedence over `included`.
elements:
  showExtensions: false
relationships:
  inheritance:
    exclude:
    - "Codable"
 ```
