### ISSUE TITLE
Support nested types in extensions and extending nested types

### ISSUE THREAD

**Issue by MarcoEidinger** [MarcoEidinger/SwiftPlantUML#69]
Related: https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/issues/26

### Example

```swift
public enum APublic {
    public enum BPublic {
        public static func publicFuncDefinedInType() {}
    }
}

// Extension is declared public, so each top level member "inherits" that access level.
public extension APublic.BPublic {
    
    // Hence this is public even if it is not annotated
    static func hasAccessLevel() -> String { return "public" }
    
    // Also this class is public
    class CPublic { // NEW: nested type defined in extension
        // However, its members must be annotated. This is public
        public static func publicFunc() {}
        
        // This is internal because no explicit access level modifier is used
        static func internalFunc() {}
    }
}

// Extension has no explicit access level modifier and therefore it is internal
// so each top level member "inherits" that access level.
extension APublic.BPublic {
    
    public static func publicFuncAddedInExtenion() {} // NEW: extending nested type
    
    class CInternal {
        public static func publicFunc() {}
    }
}

extension APublic.BPublic.CPublic {
    public static func publicFuncAddedInExtenion() {} // NEW: extending nested type

    static func internalFuncAddedInExtenion() {}
    
    private static func privateFuncAddedInExtenion() {}
}

private extension APublic.BPublic.CInternal {
    private class DPrivate {
        init() {}
    }
    
    // compiles but `DPublic` will not be accessible as it is defined in a private extension
    public class DPublic {
        public init() {}
    }
}
```

### Expected output

Note: extensions will always be rendered/processed no matter what `elements.havingAccessLevel` you specify in configuration.
- Reason:  extensions may not have an explicit access-level modifier, i.e. any type members added in an extension have the same default access level as type members declared in the original type being extended but also it is possible to set explicitly set an access  level for type member declaration.
- Example: `extension APublic.BPublic` adding new type members have a default access level of internal but you can add also `public` or `private type members. Hiding `extension APublic.BPublic` when specifying `elements.havingAccessLevel = public` would potentially result in loss of information as the extension may have added public-type members 

```yml
elements:
  showNestedTypes: true
  showExtensions: all
  havingAccessLevel:
  - public
  - internal
  - private
```

![Result](https://www.planttext.com/api/plantuml/svg/hLHBRu904BxlhvZqKecFrFPgZ2YqCJ6jAHxQumgZR8I5x2wsnkXlBwWeGKGqlP1DvdlCp7vBJoegLEHxv16ioVV8ZB_wvuIup450FrGhyD6Vef14BXWFgQ0-I9SwmG_ZSvXHJ-AHQhuRHA82JdsK8RNHmeIW0W4yu4W8iJqg9JpeusZgCVi1g8J36JeTg9aD6B6vgoo5wFMz23L07ldGxS8QW6nIVl-St-fNrI40zNKyjcBs1i8TwJNYje4pnj4Pyiagn9gMSHjSTciDCgw31XXKB2oaRmAHQwLsDIqkR8y5nXKAJhrzAMi-F5IAxTFgFGraN8onO4kgiDoabSBAtRQCCvMJBzbWHhtABi_4IyBmjDFwQi27iED4noduLSWb2tZ1QbmgTTj6AKUuHA-gHViMYzFsTST9icOcu1XxQzwU_ydrOWQBaCsJuZu6LmUfbjsNAyCaYWTolTdCoP3ybPz3qgNbeUqYQDfK7fnfjunsV2Bty_UzaXvo9_ul_m40)

---

```yml
elements:
  showNestedTypes: true
  showExtensions: all
  havingAccessLevel:
  - public
  - internal
```

![Result](https://www.planttext.com/api/plantuml/svg/hLHBJy904BxlhvXmaOP7HA-4K6Wr94IDSD3ZiXteXdRRx6vHGl2tsoA5Maefnijca_aUCpjVjgyqbJhoFN83a-dxs8vFytLANEuWe1_gDVZepr0gefPSX5HI7vHBdU23YmNCgQVmGBMVBA9GWw0-gf0od612q8444GWaX32FAWKryoMQUPpLW2hOtw7RXRhTX35Vk7gY4Rs15w41A28VUZtO091joX-Syjk3gZe4eB69nzQSRI7SaHuYmIoSSu7EI4pN8TQDZDlml5jxc74TDi6YSZb1-YWHXL5gLpVYmjUXm8L6AQZtKygQZ_QLOlkq-fS6CYvMsOYfHzkgD2mNNFyIBzdMxKxhhGdFaiMHYzVqgL4e7eY2tbsgJCPGgJ6kqAjgqRd6ulWyfkCaOR0JS8ozDX1t_-HwDYH5oDPHKV8LrNXna6hXkhymJAAu9pTQhPmCoQ_y598-MXxQAOAcJUN1cNRBQ6c82UcZSEAFxni0)

---

```yml
elements:
  showNestedTypes: true
  showExtensions: all
  havingAccessLevel:
  - public
```

![Result](https://www.planttext.com/api/plantuml/svg/hLHBJy904BxlhvXmaKOWwfaG7gs6XAYn7FIuR0UwOJjjThSe8VZRRP6N1GeaNZQRpFUOcM-pRMEvjccas0tumu-1bvsTjo4BPO20KMBd464qGcsOcKfAkEOHc907yQUa2OovChYbUiykCsY1U8GcuG9zp0asra0n8MDCA6uCL3glwKX9KG5kO7s7PXEgNWq6SX9QtoAghahH0QGqWbOB5W1ikU5t3_cDxgKw3E1saOrjfLX2iY8zfYHS74l2e4_3UO9LPy-jTzgjqTjpxTN0vNhg8t_IYEIKsbMThF2zBKYog8chtzAUkLjctb-p6kv5RKYIzezuoHxlLbhlDNZH8diCsGA_B9AHCHqPA-Ic8mGQCy0Pgaijxg-ns6sk4mHvJ5uEph3NHlNmJwudupk6hEyKjPnnYsS7sKHR7loPMNB1DVUsNY-ei6BYXv3DpehGNGF7ECLNoLWRASZ-c1y0)

---

```yml
elements:
  showNestedTypes: true
  showExtensions: merged
  havingAccessLevel:
  - public
  - internal
  - private
```

![Result](https://www.planttext.com/api/plantuml/svg/dLHBRu904BxlhvXuQ2K-Ve4nej36n3IcUEbnXL4sBWFPNMoDqTzUjV8eLaAza2NpFMS98ssuCcaasJDuYu-PUthQxmiMYW01eyJi8C9eYKeplH6KSCKZq24Fuaz1QrXngJ6dkcyEqsY0U8GwuJvwU2QOM075X8mnNtAjeMNFqwKKVWkuXkiP1WDekrsOYNLeF8Cenp952v3I28P3s0EmGyOVt_BxuwOw3A2pFzKsmZz0SY6zfEGxk1A4mPGMkmJRrYzKoBNj-wZr3BSesnOCdfQnDCCxKdOGd8NSBuCaOYhmfGgJ-nNwarALIHSShZOUybU5I5PjXqliOpuGP50Hb_deNs7lIjKnUeM34bjkiF4-fbU7lpUIJH_PISd5cV-agZVfPx1wjwCWOIhoDPTQKczolONuLQdJwrKqMUNz5f5zIasGMRugjfZKiVATFKp_2Sf6IC7fV_GD)

---

```yml
elements:
  showNestedTypes: true
  showExtensions: merged
  havingAccessLevel:
  - public
  - internal
```

![Result](https://www.planttext.com/api/plantuml/svg/dLFBRi8m4BpxArOSMY8UNu1G0qah95HL3PSUbsGX5lOciXrQXEYt5oW12YLAUuaSxJnsnlA3TMXSePMuXsZoDWwtN_zr8bAP493EtGeqwIaPA-n2Seu6DTWKa-nTyXncg2mTgU5p82mvODHaSumfeXt1PGOuOn92n0gjXOR_KaoLZ1k05WvdwFMW6RPXBEUfYnoH6gY2F20kDFJxi0OGcv8_kEPt1tLr141hlOtjPBo1V4zwB3WEQ2QPaX5FLZarlH-e5AqVnsJjc9QacXxqxgQPSlqRKdwIx8J23qSiCpxXpo8CRqVe3i-Y3DiGe5b4X4-6YBtA3FkrFuy3oOuCepgE_hJiJQagHkVaOEGI7TNkOtHm-BsHSlgVJivSWghMIuzkKAj_oT9zYn-KMftEXQQu-Bz6b7TT1rdkTuazJQfOPIeX7eYJxOl_0W00)

---

```yml
elements:
  showNestedTypes: true
  showExtensions: merged
  havingAccessLevel:
  - public
```

![Result](https://www.planttext.com/api/plantuml/svg/bLFBRi8m4BpxArOSMY8UNu0GWQGL4gggXakFYxCG2tiJsGujGlJR6n056WgY5skjdPcTMSi3vz7wqcZn2CdqVH9NP_Ws5PbA2SWKVWs6p8oi4swfk42B1bo6QVwXU05pr8wErFWb4euyC1fo1KfAQ4VmkGNEcOGGKgDpq0XVovbMiW7eu513hmVDk0qJjSXyuedqK9SK075feD-73O3O_l27b_pky5uT0T3QLB6zabiezgIdacL4SyMKZdcwBgWP_49bw48foRa9hKWt0-Wzp7Bj-rUamZJT2SMVdbZbVCAVHHXTZz0TdKKPjI52kqm8doqH1pSpx6r_7HkAFLb6VMpzo-nLgLkCpcc2LIlqTEy-eblx61-cTwExDgDO-Mf89NvGQdKwDKrHkryYVbwXZZov-OjJToh4W3Yj_jSt)

---

```yml
elements:
  showNestedTypes: false
  showExtensions: all
  havingAccessLevel:
  - public
  - internal
  - private
```

![Result](https://www.planttext.com/api/plantuml/svg/bPB1IWCn54Nt-Of7DxPOYnzGIcVg28L1nUb2bsdox0IJDqDUfYgbVhiPRQkYjNOJ0hddNWvap47wq3WhJg2OtUTPF9FRcIYDHa1NXnTmwEReMV2ZeLfwwO1BgQidGmjua9PnXsPN5u8n04c7N4k51RP0g3nGHIY4K5OoGoUvQURMg0v8XiqTXaFePdt8pQ8CHK2qgMsm1qYDWz48LW1YlUNJd_mW_T9pruThhw93v9y34fkAFae4mEagEWUZrb1AJfH2vXoNQBkz_osS7pDHloEN3Qb4QzHJojfmp7vRc-nV6qoEz_fZDEPUTpb30Jr9kozvzjdepL86FEWntJJ-Rh9zFU3I5WenHjBnNxu1)
