### ISSUE TITLE
Turns out whitespace is important

### ISSUE THREAD

**Issue by benadamdev** [MarcoEidinger/SwiftPlantUML#70]
When setting relationships between elements, it turns out that A+--B and A<space>+--<space>B yield different results visually. Not using spaces even results in errors. Please have a look at the attached images. SwiftPlantUML doesn't include spaces in the relationships.

<img width="762" alt="no_space" src="https://github.com/MarcoEidinger/SwiftPlantUML/assets/58568911/dbaa604c-ede7-4cc0-aff7-b22671472d22">
<img width="521" alt="with_space" src="https://github.com/MarcoEidinger/SwiftPlantUML/assets/58568911/497d262e-5d9b-477d-9ecb-fbe1dc231887">

**Comment by benadamdev** [comment]
Here is the code I used :
```
@startuml
!theme plain
' STYLE START
hide empty members
skinparam shadowing false
' STYLE END

title
SubscriptionLocalizationCreateRequest
end title


class "SLCreateRequest" as SLCreateRequest << (S, SkyBlue) struct >> { 
  +data : Data
  +init(data:)
  +init(from:)
  +encode(to:) 
}
class "Data" as Data << (S, SkyBlue) struct >> { 
  +type : `Type`
  +attributes : Attributes
  +relationships : Relationships
  +init(type:attributes:relationships:)
  +init(from:)
  +encode(to:) 
}
class "Type" as Type << (E, LightSteelBlue) enum >> { 
  +subscriptionLocalizations 
}
class "Attributes" as Attributes << (S, SkyBlue) struct >> { 
  +name : String
  +locale : String
  +description : String?
  +init(name:locale:description:)
  +init(from:)
  +encode(to:) 
}
class "Relationships" as Relationships << (S, SkyBlue) struct >> { 
  +subscription : Subscription
  +init(subscription:)
  +init(from:)
  +encode(to:) 
}
class "Subscription" as Subscription << (S, SkyBlue) struct >> { 
  +data : Data
  +init(data:)
  +init(from:)
  +encode(to:) 
}
class "Data" as Data0 << (S, SkyBlue) struct >> { 
  +type : `Type`
  +id : String
  +init(type:id:)
  +init(from:)
  +encode(to:) 
}
class "Type" as Type1 << (E, LightSteelBlue) enum >> { 
  +subscriptions 
}
SLCreateRequest +-- Data
Data +-- Type
Data +-- Attributes
Data +-- Relationships
Relationships +-- Subscription
Subscription +-- Data0
Data0 +-- Type1

@enduml

```

**Comment by MarcoEidinger** [comment]
@benadamdev It would be great if you can answer the following questions to help me figure out how to reproduce the issue you encounter

- Which SwiftPlantUML version are you using?
- Do you use a custom `.swiftplantuml` configuration file (if yes please share) or which command-line options do you set?
- Are you able to post the respective Swift code you are using from which you generate the incorrect diagram?

**Comment by benadamdev** [comment]
@MarcoEidinger Hi. I use the `swiftplantuml` tool not the `SwiftPlantUML` Swift package. The version is `0.7.3`.
The command I use to generate the class diagram is: `swiftplantuml classdiagram  --output consoleOnly > docs/class_diagram.uml`

Here are the `.swiftplantuml` contents:

```yaml
files:
    include:
    - SubscriptionLocalizationCreateRequest.swift
    # exclude:
    # - "*.swift"
elements:
  showMemberAccessLevelAttribute: true
  havingAccessLevel:
  - public
  - open
  showMembersWithAccessLevel:
  - public
  - open
  showNestedTypes: true
  showExtensions: merged
theme: plain # see https://plantuml.com/theme
texts:
  title: SubscriptionLocalizationCreateRequest
# skinparamCommands: # see https://plantuml.com/skinparam
# - skinparam classBackgroundColor PaleGreen
# - skinparam classArrowColor SeaGreen
# - skinparam classBorderColor SpringGreen
# - skinparam stereotypeCBackgroundColor YellowGreen
# - skinparam stereotypeCBackgroundColor<< Foo >> DimGray
relationships:
  inheritance:
    label: "inherits from"
    style:
      lineStyle: dotted
      lineColor: DarkViolet
      textColor: DarkViolet
    exclude:
    - Codable
    - Identifiable
    - CaseIterable
    - String
```
